language: go
go:
- 1.10.x
- 1.11
before_install:
- go get -u github.com/mattn/goveralls
script:
- go build
- goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
git:
  depth: 3
notifications:
  email: false
  slack:
    secure: Iij0OxR+dDghvtYtYZInp9951xjgTmQ/8vew+o3lYQS+sOaK+tnDM8d+O2FrFveaUqZ2jJ/wBFK3zXsPpmFoTu+0u6aj8dIryXMC/61yEQiKJh3MXsLkluNfRnE63HgO40YGnC31QLmx3elEVESIpXc+XTQUjTrIV6QroLjAXCjQslOAbPPxsHq/s7sOuUc2zBMGEAv/EIQYsF21WT6VYYdCV6dlKeahsqXF3Va0P0Ml1lJl195o/tVQyoT6lBSlNnczKw0tIBYEHzOOQ/vm7D2rgRexmMhD81oYycmlrxlUQ7lKxYaMQ63SW+smbtBikAqb5dat2/kYBgrpwIbCzzrLPUp8tBxYdz+Eur0zZqO+zpvGlBDkcbl+r3EmaQZ7Kwuuf+TcCx6uI7c5tfjmlToZoZMA0SIEIHrtu6VpThNoEdYJcTN9pRaCZHmXDeCvrg+zPJbcau4br3uGqzagIfDvREIYTd6l0vcpLjbF2g1E9Ps9iYl2mi7DTsTkv1qbiVoMejTBjZZbKJrXVg5d3kBBOMpRBm+Id43o/6Si75oftJxcczmdZn9iyN79QBEvFqt2VJ3a1ChSjaiW4Qaq81d3c+b6M8PEht9Zip4XGzCGo3uD2VOIlUbOh9GgnsgeIgUkxYbqLzlXxuU1A3HlYe3Tt9odCZmfAvOT/Y6eEk8=
env:
  global:
    - GO111MODULE=on
    - secure: U1+pm85NzpMweqtKApwSdgNfPnCDOxJ/0v5yJTydD6q/qZqkaFDwIyiGN9NF78gT4ORo+Egzfg/Pi/D4/JI3GEkRcChZ8kNnYNczl2bXs1e1O5TpfNSVPBjFYLpaNSKcAdGEWiJ4WFgHHmsK7kaYz0hL/ERZsiIUme98rgeGXi4o3lARfAcR+cd9sXoRWO+kzwQF8ZVE0odKrI0oWDrDDIz/eBIlDOKlj0xZBN5Tzbg7s6fQW+AGGmpAOWAP1mZVVNaTaFMfhEJtAYa81/KCYYd7BFs+dUlgWgDPuNaC1FpC6+xlXlWocNMi/DGg7FiO1Vo+2ZnWQ3O6WPSBDGAv9/BMDN52rquHC6NKRd2dMQxwzgkOKy4QYEn2SPDJExgQ6qavSErtt+6fkmlGicWcby+TFc1Md7zYb+uIxjP+3Do8fTqQsxbjVfVpCyvP/MnHn2TITIRLWLvq8Qq9x6JFBqxjU4P+tbiBxY9dqV+zqBa0s79oocflihRVeYHWu8KtYpRaAYES/xvMOg4pOIk+Z5SUJkESxzyX7AV9KmpOlBWP2A1+SLY0VB8Cn63zrSBlMcj+vK2/wYRV+14mZRlUuesjGAvEE70XOPcyBacezYMu/c1u9Ot0UclieSVCwR4bbF5oPpwOJFFSCS2e4Hspzno2e4kGM/iXk9rYnDGTJm0=
